#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Tutorial1.Resource", IsApplication=true)]

namespace Tutorial1
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int monoandroidsplash = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f06000f
			public const int MyButton = 2131099663;
			
			// aapt resource value: 0x7f060005
			public const int btnCreateDb = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int btnCreateTbl = 2131099654;
			
			// aapt resource value: 0x7f06000c
			public const int btnCrud = 2131099660;
			
			// aapt resource value: 0x7f060003
			public const int btnCrudAdd = 2131099651;
			
			// aapt resource value: 0x7f060002
			public const int btnCrudSave = 2131099650;
			
			// aapt resource value: 0x7f06000b
			public const int btnDelete = 2131099659;
			
			// aapt resource value: 0x7f060007
			public const int btnInsert = 2131099655;
			
			// aapt resource value: 0x7f060013
			public const int btnRemoveSearch = 2131099667;
			
			// aapt resource value: 0x7f060015
			public const int btnRemoveTask = 2131099669;
			
			// aapt resource value: 0x7f06000e
			public const int btnSave = 2131099662;
			
			// aapt resource value: 0x7f060017
			public const int btnSearch = 2131099671;
			
			// aapt resource value: 0x7f060019
			public const int btnSearchById = 2131099673;
			
			// aapt resource value: 0x7f060008
			public const int btnSelectAll = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int btnSelectById = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int btnUpdate = 2131099658;
			
			// aapt resource value: 0x7f06001a
			public const int btnUpdateById = 2131099674;
			
			// aapt resource value: 0x7f060004
			public const int lstCrud = 2131099652;
			
			// aapt resource value: 0x7f060000
			public const int textView1 = 2131099648;
			
			// aapt resource value: 0x7f060010
			public const int textView2 = 2131099664;
			
			// aapt resource value: 0x7f060012
			public const int textView3 = 2131099666;
			
			// aapt resource value: 0x7f060001
			public const int txtCrudTask = 2131099649;
			
			// aapt resource value: 0x7f060018
			public const int txtId = 2131099672;
			
			// aapt resource value: 0x7f060011
			public const int txtRemoveId = 2131099665;
			
			// aapt resource value: 0x7f060014
			public const int txtRemoveTask = 2131099668;
			
			// aapt resource value: 0x7f060016
			public const int txtSearch = 2131099670;
			
			// aapt resource value: 0x7f06000d
			public const int txtTask = 2131099661;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int CrudFormLayout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int CrudLayout = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Home = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int InserTask = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Main = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int RemoveTask = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int SearchResult = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int UpdateTask = 2130903047;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int Mono_Android_Theme_Splash = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
